### ISSUE TITLE
Mouse Unusable (e.g., Logitech MX Master 3)，When using a combined keyboard and mouse receiver。

### ISSUE THREAD

**Issue by zoushiyin** [No0ne/ps2x2pico#61] opened 2024-11-19 12:37 UTC
When using a combined keyboard and mouse receiver, the mouse (e.g., Logitech MX Master 3) is not functioning properly. Specifically, the mouse does not work at all. We would like to know if this issue is specific to the Logitech MX Master 3 or if other Logitech mice also experience similar problems.

**Comment by zoushiyin** [comment] 2024-11-19 12:47
Yes, I tried version pre-1.3. The issue still persists with this version.

Thank you for your help!

**Comment by No0ne** [comment] 2024-11-19 12:50
Which color does the logo on the USB receiver have?

**Comment by yarodin** [comment] 2024-11-19 16:43
I have MX Master 3S mouse and MX Mechanical Mini plugged through combined keyboard and mouse receiver (bolt, light green logo) without any issues on version pre-1.3

**Comment by No0ne** [comment] 2024-11-20 06:07
Can you hook up a serial debug cable to GPIO0 and post the output?

**Comment by zoushiyin** [comment] 2024-11-20 06:08
The receiver is black, and the logo on it is "logi" in lowercase letters, not the "G" logo.

I tested with the latest version today, and the issue still persists. The mouse is not recognized at all; the cursor doesn't even move.

However, the Logitech receiver with the "G" logo works fine.

Thank you for your help!

**Comment by No0ne** [comment] 2024-11-20 06:10
Can you hook up a serial debug cable to GPIO0 and post the output?

**Comment by No0ne** [comment] 2024-11-20 06:19
Ah I've got a mouse now so I can reproduce this, I'll get back to you!

**Comment by zoushiyin** [comment] 2024-11-20 06:32
Thank you very much! I am waiting for your response online.

**Comment by No0ne** [comment] 2024-11-20 09:34
It seems it depends on whether the receiver is connected to a hub or directly to the pico 🤔

**Comment by zoushiyin** [comment] 2024-11-20 11:51
I usually connect it to a hub, but it doesn't work even when I connect it directly during testing. Also, we need to use a hub to connect both the keyboard and the mouse.

Is there any good solution or workaround for this issue?

**Comment by No0ne** [comment] 2024-11-20 11:53
I think I know where the issue is, its in the mouse report initialization, I'll get back to you!

**Comment by No0ne** [comment] 2024-11-21 14:21
Should be fixed in the latest pre-release: https://github.com/No0ne/ps2x2pico/releases/tag/pre-1.3
If not please leave a comment.

**Closed by No0ne** 2024-11-21 14:21 UTC
