### ISSUE TITLE
Inverted Y-Axis

### ISSUE THREAD

**Issue by anderssonbilly** [No0ne/ps2x2pico#3] opened 2022-11-17 23:00 UTC
Hi.

Just finished building the adapter and it all works great except I got some issues with the mouse.
My test system is a Pentium III WinME computer and a Razor DeathAdder USB mouse.
The keyboard works fine, but the mouse Y-Axis is inverted.

**Comment by No0ne** [comment] 2022-12-04 20:53
Only the Y-Axis is inverted and everything else correct?
Will address the "Mouse Issues #1" first and afterwards add DIP-switches or jumpers for inverting axis.

**Comment by anderssonbilly** [comment] 2022-12-04 22:32
With the mouse, yes, only the Y-Axis is inverted other than that it works great.
A DIP-switch to invert the axis could be really useful in some DOS games.
Curious thou why my mouse is inverted.

If there is anything I could do to help troubleshoot just tell me.

**Comment by anderssonbilly** [comment] 2022-12-05 23:14
`HID device address = 1, instance = 0 is mounted
HID Interface Protocol = Mouse
00 00 00 00
00 00 00 00
00 01 01 00
00 00 01 00
00 00 01 00
00 00 01 00
00 00 01 00
00 00 01 00
00 00 02 00
00 00 01 00
00 00 01 00
00 fd 02 00
00 00 01 00
00 00 01 00
00 ff 02 00
00 00 01 00
00 ff 02 00
00 00 01 00
00 00 01 00
00 00 02 00
00 00 01 00
00 00 01 00
00 00 01 00
00 ff 02 00
00 fe 01 00
00 00 01 00
00 00 01 00
00 ff 02 00
00 00 01 00
00 00 01 00
00 00 02 00
00 00 02 00
00 00 01 00
00 ff 01 00
00 00 02 00
00 00 02 00
00 ff 02 00
00 00 01 00
00 00 04 00
00 00 01 00
00 00 02 00
00 00 02 00
00 ff 02 00
00 00 02 00
00 00 02 00
00 02 02 00
00 01 01 00
00 00 03 00
00 00 02 00
00 00 02 00
00 00 02 00
00 00 02 00
00 00 02 00
00 00 03 00
00 00 02 00
00 00 02 00
00 00 02 00
00 00 02 00
00 00 02 00
00 00 02 00
00 00 02 00
00 00 01 00
00 00 02 00
00 00 02 00
00 00 02 00
00 00 01 00
00 00 01 00
00 00 02 00
00 fd 01 00
00 00 01 00
00 00 01 00
00 00 01 00
00 ff 00 00
00 00 fd 00
00 00 ff 00
00 00 ff 00
00 00 ff 00
00 00 ff 00
00 00 ff 00
00 00 ff 00
00 00 fe 00
00 00 fe 00
00 00 ff 00
00 00 ff 00
00 00 fe 00
00 00 ff 00
00 02 fe 00
00 00 fe 00
00 01 ff 00
00 00 ff 00
00 00 fe 00
00 01 ff 00
00 00 ff 00
00 00 ff 00
00 00 fe 00
00 00 ff 00
00 00 ff 00
00 00 ff 00
00 00 ff 00
00 01 fe 00
00 00 ff 00
00 00 ff 00
00 00 ff 00
00 01 ff 00
00 00 fe 00
00 00 ff 00
00 00 ff 00
00 01 00 00
00 00 fe 00
00 00 ff 00
00 00 ff 00
00 01 fe 00
00 00 ff 00
00 00 ff 00
00 00 ff 00
00 00 ff 00
00 00 ff 00
00 00 ff 00
00 00 ff 00
00 00 ff 00
00 00 ff 00
00 00 ff 00
00 00 ff 00
00 00 ff 00
00 01 ff 00
00 00 fe 00
00 00 ff 00
00 01 fe 00
00 00 ff 00
00 00 ff 00
00 01 fe 00
00 00 fe 00
00 00 ff 00
00 01 fe 00
00 00 fe 00
00 00 fe 00
00 00 fe 00
00 00 ff 00
00 01 fe 00
00 00 fe 00
00 01 fe 00
00 00 fe 00
00 00 fe 00
00 01 ff 00
00 00 fe 00
00 00 ff 00
00 02 fe 00
00 00 ff 00
00 00 ff 00
00 00 fe 00
00 00 ff 00
00 00 ff 00
00 00 fe 00
00 00 ff 00
00 00 fe 00
00 00 ff 00
00 00 ff 00
00 00 fe 00
00 00 ff 00
00 01 fe 00
00 00 fe 00
00 00 ff 00
00 01 fe 00
00 00 ff 00
00 00 fe 00
00 01 ff 00
00 00 fe 00
00 00 ff 00
00 01 fe 00
00 00 ff 00
00 00 ff 00
00 00 fe 00
00 00 fe 00
00 00 ff 00
00 01 ff 00
00 00 ff 00
00 00 fe 00
00 00 ff 00
00 00 ff 00
00 00 ff 00
00 00 ff 00
00 fd 00 00
00 ff 00 00
00 ff 00 00
00 ff 00 00
00 ff 00 00
00 ff 00 00
00 ff 00 00
00 ff 00 00
00 ff 00 00
00 ff 00 00
00 ff 00 00
00 ff 00 00
00 02 00 00
00 01 00 00
00 01 00 00
00 02 00 00
00 01 00 00
00 01 00 00
00 01 00 00
00 04 00 00
00 00 02 00
00 01 00 00
00 01 00 00
00 01 01 00
00 01 00 00
00 02 00 00
00 01 00 00
00 00 01 00
00 01 00 00
00 01 00 00
00 00 01 00
00 02 00 00
00 01 01 00
00 01 00 00
00 01 01 00
00 02 01 00
00 01 00 00
00 01 00 00
00 01 01 00
00 01 01 00
00 01 01 00
00 02 00 00
00 01 01 00
00 01 00 00
00 02 01 00
00 02 00 00
00 00 01 00
00 02 00 00
00 01 01 00
00 02 01 00
00 01 01 00
00 03 01 00
00 00 01 00
00 02 01 00
00 02 01 00
00 01 01 00
00 02 00 00
00 02 01 00
00 00 01 00
00 03 01 00
00 02 01 00
00 02 00 00
00 02 01 00
00 02 01 00
00 02 01 00
00 01 01 00
00 02 00 00
00 02 01 00
00 02 01 00
00 02 01 00
00 01 00 00
00 00 01 00
00 02 01 00
00 02 00 00
00 01 01 00
00 02 00 00
00 02 01 00
00 00 01 00
00 03 00 00
00 01 00 00
00 01 01 00
00 02 01 00
00 01 00 00
00 01 00 00
00 00 01 00
00 02 00 00
00 01 01 00
00 02 00 00
00 01 00 00
00 02 01 00
00 01 00 00
00 01 00 00
00 02 01 00
00 01 00 00
00 00 01 00
00 01 00 00
00 00 01 00
00 02 00 00
00 01 01 00
00 01 00 00
00 01 00 00
00 01 00 00
00 01 01 00
00 01 01 00
00 01 00 00
00 01 00 00
00 00 01 00
00 01 00 00
00 01 00 00
00 01 00 00
00 00 01 00
00 00 01 00
00 01 00 00
00 01 00 00
00 01 01 00
00 01 00 00
00 01 00 00
00 00 01 00
00 00 01 00
00 02 00 00
00 01 01 00
00 01 00 00
00 00 01 00
00 01 00 00
00 01 00 00
00 01 01 00
00 01 00 00
00 01 00 00
00 00 01 00
00 01 01 00
00 01 00 00
00 01 01 00
00 01 00 00
00 00 01 00
00 01 00 00
00 01 00 00
00 01 00 00
00 01 00 00
00 00 01 00
00 01 00 00
`

Here I got some data from my Razor mouse.
I moved up then down, left and right.

**Comment by serisman** [comment] 2022-12-05 23:58
> Sorry for no newline, how do I markdown that in github? Thought it was four spaces.

Triple backticks

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by anderssonbilly** [comment] 2022-12-06 20:55
I used the latest release but I'll try to compile latest my self and report the result as soon as I got some time over.

**Comment by No0ne** [comment] 2022-12-07 20:21
@serisman The additional info is missing because the mouse port was not in streaming mode.

**Comment by No0ne** [comment] 2022-12-14 18:51
hm @anderssonbilly your mouse is indeed repoting the y-axis inverted 🤔
here is mine:
```
UP
00 00 ff 00
00 00 ff 00
00 00 fe 00
00 01 ff 00
00 00 ff 00
00 00 ff 00
00 00 fe 00
00 00 ff 00
00 00 ff 00
00 00 ff 00
00 00 ff 00
00 01 ff 00
00 00 ff 00
```

```
DOWN
00 00 01 00
00 00 01 00
00 00 02 00
00 00 02 00
00 00 02 00
00 01 03 00
00 01 03 00
00 01 03 00
00 00 03 00
00 01 04 00
00 00 04 00
00 01 04 00
00 00 04 00
00 01 04 00
00 01 03 00
00 00 02 00
```

```
LEFT
00 fd 00 00
00 fd 00 00
00 fd 00 00
00 fd 00 00
00 fe 00 00
00 fe 00 00
00 fe 00 00
00 fe 00 00
00 fe 00 00
00 fe 00 00
00 ff 00 00
00 ff 00 00
```

```
RIGHT
00 01 00 00
00 01 00 00
00 01 00 00
00 02 01 00
00 02 00 00
00 02 00 00
00 02 01 00
00 02 00 00
00 02 00 00
00 03 01 00
00 03 00 00
00 03 01 00
00 03 00 00
00 04 01 00
00 03 00 00
00 03 01 00
00 03 00 00
00 04 01 00
00 03 00 00
```

**Comment by No0ne** [comment] 2023-01-28 17:52
@anderssonbilly sorry for the delay (have no permissions to send PMs on vogons)
I'm currently out of time, may be I'll continue work in spring or summer.
You could also look into https://github.com/rasteri/HIDman which made good progress I think.

**Comment by No0ne** [comment] 2023-09-20 11:00
Please try the [fork by anteo](/anteo/ps2pico4zx) which runs the mouse in report mode. I will likely do report mode in my repo too.

**Comment by No0ne** [comment] 2023-10-23 18:43
Recently I came across a Razor which also had inverted Y-Axis in the BIOS. So I will be testing with that soon.

**Comment by anderssonbilly** [comment] 2023-11-14 22:06
@No0ne sorry for the late reply, have had way to little time for hobby projects latley.
Did you get anywhere with the Razor mouse?

**Comment by No0ne** [comment] 2023-11-15 06:45
Sorry no, didn't have time atm. Could you test with the [fork by anteo](https://github.com/anteo/ps2pico4zx)?

**Comment by anderssonbilly** [comment] 2023-11-23 00:57
Link seems to be dead. Do you have a backup?

**Comment by No0ne** [comment] 2023-11-23 07:12
Fork seems to be gone 🤨

**Comment by No0ne** [comment] 2024-03-02 17:20
@anderssonbilly could you please retry if the inverted axis is fixed with one of these two updates?
https://github.com/No0ne/ps2x2pico/raw/24-ps2-input/ps2x2pico-boot.uf2
https://github.com/No0ne/ps2x2pico/raw/24-ps2-input/ps2x2pico-report.uf2

**Comment by No0ne** [comment] 2024-06-21 09:03
Also got a Razor DeathAdder Model RZ01-03850 but I can't reproduce the problem with the recent version 0.9-1.1!
Maybe the TinyUSB library upgrade fixed the problem.

**Closed by No0ne** 2024-06-21 09:03 UTC

**Comment by No0ne** [comment] 2024-11-16 16:37
Please try the new pre-release: https://github.com/No0ne/ps2x2pico/releases/tag/pre-1.3
