### ISSUE TITLE
Mouse issues when using PS/2 to USB adaper

### ISSUE THREAD

**Issue by naplesap** [No0ne/ps2x2pico#29] opened 2024-03-25 09:52 UTC
First of all, love this project. I've used it numerous times on PiKVM v2 but now I'm running into a unique issue. I have a device that has independent USB mouse and keyboard inputs. I used the Pico HID to convert the HID to PS/2, then two independent PS/2 > USB adapters to convert back to USB. Is there an easy way to tweak the code to allow the Pico to just isolate Keyboard from Mouse and output to two separate USB-A? Forgive my lack of coding knowledge.

My problem when using Pico Bridge on PiKVM v4+ is when converting the PS/2 mouse back to USB the screen scrolls when I move the mouse up and down as if I am holding down a scroll wheel or mouse button.

![image](https://github.com/No0ne/ps2x2pico/assets/164865558/37d402ac-7c19-4974-baa4-82bb3f872efa)

**Comment by No0ne** [comment] 2024-03-25 10:13
Hi, thats an interessting usecase! I think this should be possible using this project: https://github.com/sekigon-gonnoc/Pico-PIO-USB

You only would need a Pico, four 22 ohm resistors and two USB-A plugs. Do you have this on hand for testing?

Which PS/2 to USB adapters are you using? Maybe I could fix the mouse wheel issue.

**Comment by naplesap** [comment] 2024-03-25 10:37
I only currently have 4.7k ohm and 390 ohm resistors on hand, however I could easily order 22 ohm. I've tried both of the following PS/2 > USB adaptors with the same result:

https://www.amazon.com/gp/product/B00IACID2C/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
https://www.amazon.com/gp/product/B00028OP2Y/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1

**Comment by naplesap** [comment] 2024-03-25 11:15
I have ordered 22 ohm resistors that should be here in about 12 hours. I appreciate your help.

**Comment by No0ne** [comment] 2024-03-25 15:00
And the mouse wheel issue is exactly the same with both PS/2 adapters?

**Comment by naplesap** [comment] 2024-03-25 15:15
> And the mouse wheel issue is exactly the same with both PS/2 adapters?

Yes, the issue is exactly the same.

**Comment by No0ne** [comment] 2024-03-25 16:57
I ordered the startech one do I can reproduce/fix that.

**Comment by naplesap** [comment] 2024-03-25 17:13
> I think this should be possible using this project: https://github.com/sekigon-gonnoc/Pico-PIO-USB
> 
> You only would need a Pico, four 22 ohm resistors and two USB-A plugs. Do you have this on hand for testing?
> 
I'm going to test this in a few hours. Do you happen to know if there is a video or instruction manual for the Pico-PIO-USB?

**Comment by No0ne** [comment] 2024-03-25 17:52
This is mainly a library and not a finished project. You could take a look in the examples folder I guess. I'll be able to try a pikvm integration after the easter holidays.

**Comment by No0ne** [comment] 2024-03-26 15:55
Got the Startech adapter today, tested it and it works fine. 😲 
Maybe there was a fix since the last release, I'll build you a custom pikvm version with the 1.0 pre-release.

**Comment by naplesap** [comment] 2024-03-27 12:58
> Got the Startech adapter today, tested it and it works fine. 😲 Maybe there was a fix since the last release, I'll build you a custom pikvm version with the 1.0 pre-release.

That is far too kind of you. I really appreciate that. In the meantime I'm going to try to tinker with the Pico PIO USB and see if I can get that to work. Thanks again!

**Comment by No0ne** [comment] 2024-03-27 19:13
I asked if it is possible to generate two devices via the PIOs as I saw no obvious way to do so: https://github.com/sekigon-gonnoc/Pico-PIO-USB/issues/114

**Comment by naplesap** [comment] 2024-03-28 13:16
Testing it now and the issue seems to be the same. If i move the mouse up or down slowly the cursor barely moves but the page in the background seems to scroll insanely fast.

**Comment by No0ne** [comment] 2024-03-28 13:18
Did you also update pikvm it self via `[root@pi4kvm ~]# pikvm-update` ?
Which browser/OS are you using on the host system?

**Comment by naplesap** [comment] 2024-03-28 13:35
> Did you also update pikvm it self via `[root@pi4kvm ~]# pikvm-update` ? Which browser/OS are you using on the host system?

I just updated to the latest pikvm version. I'm using Win11 and Chrome Version 123.0.6312.59 (Official Build) (64-bit)

**Comment by No0ne** [comment] 2024-03-28 14:02
[hid-no-wheel.zip](https://github.com/No0ne/ps2x2pico/files/14790638/hid-no-wheel.zip)
Please try this, it forces a two button mouse without wheel.

**Comment by naplesap** [comment] 2024-03-28 15:18
> [hid-no-wheel.zip](https://github.com/No0ne/ps2x2pico/files/14790638/hid-no-wheel.zip) Please try this, it forces a two button mouse without wheel.

I've tried this too, and it still seems to be doing the same thing. I'm stumped. The little top mouse icon in the top-right flashes green and orange whenever I move the cursor, too.

**Comment by No0ne** [comment] 2024-03-28 15:21
The flashing icon is correct as it indicates the bus busy state.
Does it still scroll? The simulate mouse should not have a wheel at the moment.
Are you shure the uf2 is on the pico?
Do you have a usb serial adapter or another pico you can hook up to the serial tx pin?
I could build you a serial debug version for further testing.

**Comment by naplesap** [comment] 2024-03-28 17:31
> Does it still scroll? The simulate mouse should not have a wheel at the moment. Are you shure the uf2 is on the pico? Do you have a usb serial adapter or another pico you can hook up to the serial tx pin? I could build you a serial debug version for further testing.

The mouse wheel no longer works but it is somehow still scrolling when I move the cursor. I made sure to run [flash_nuke] before installing the latest uf2. I do have a spare pico.

**Comment by No0ne** [comment] 2024-03-28 17:33
Does the scrolling still happen if you plug the Startech mouse into a laptop?

**Comment by naplesap** [comment] 2024-03-28 17:45
> Does the scrolling still happen if you plug the Startech mouse into a laptop?

It seems to work fine when connected to a PC

**Comment by No0ne** [comment] 2024-03-28 17:47
🤔 Do you have a real PS/2 mouse? What happens if you connect it to the Startech and then to your device?

**Comment by naplesap** [comment] 2024-03-28 17:50
> 🤔 Do you have a real PS/2 mouse? What happens if you connect it to the Startech and then to your device?

I do not have an actual PS/2 mouse

**Comment by No0ne** [comment] 2024-03-28 17:51
If you try [pico-hid-1.0-pre.zip](https://github.com/No0ne/ps2x2pico/files/14789771/pico-hid-1.0-pre.zip) with the PC does scrolling work normal?

**Comment by naplesap** [comment] 2024-03-28 17:56
Is there any way possible to maybe use PS/2 keyboard simultaneously with the pikvm HID mouse output?

**Comment by naplesap** [comment] 2024-03-28 18:02
> > Is there any way possible to maybe use PS/2 keyboard simultaneously with the pikvm HID mouse output?
> 
> You mean on the pikvm v4 without gpio?

Yes. I'm at a unique crossroads: My device has a video output of 1920x1080 60hz so I cannot get video on pikvm v2 but the mouse works perfectly. On V4 the video works but I'm having the mouse issues. haha

**Comment by No0ne** [comment] 2024-03-28 18:07
@mdevaev should know that

**Comment by mdevaev** [comment] 2024-03-28 18:33
> Is there any way possible to maybe use PS/2 keyboard simultaneously with the pikvm HID mouse output?

No, right now it's not possible.

**Comment by naplesap** [comment] 2024-04-05 16:31
![image](https://github.com/No0ne/ps2x2pico/assets/164865558/ef61ae27-add1-429c-9c1b-e9b7a46f673f)
Hey, sorry for the delayed reply. I was out of town for a couple days. Yes, my v4+ does have the jumpers shown in the picture.

**Comment by naplesap** [comment] 2024-04-05 16:38
> ![image](https://private-user-images.githubusercontent.com/164865558/320074806-ef61ae27-add1-429c-9c1b-e9b7a46f673f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMzUwNDEsIm5iZiI6MTcxMjMzNDc0MSwicGF0aCI6Ii8xNjQ4NjU1NTgvMzIwMDc0ODA2LWVmNjFhZTI3LWFkZDEtNDI5Yy05YzFiLWU5YjdhNDZmNjczZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNVQxNjMyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGI4Y2YzMWFhYzcyYzZlYWI0Yzg2ZTA2YWQ1YWQwOGJkMDVmOTk3YWM3NGNhZWRiYThiNzExYTNiZTM5ZGFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.POTM5T1Az0r7IsnPiR9uGe1Z7gerv0TtTWUn5nRZ31Q) Hey, sorry for the delayed reply. I was out of town for a couple days. Yes, my v4+ does have the header shown in the picture.

![image](https://github.com/No0ne/ps2x2pico/assets/164865558/78a701a4-1ce8-402a-9d87-c06cd920364c)
However it appears they're used to connect to the top board:
![image](https://github.com/No0ne/ps2x2pico/assets/164865558/f8793136-a741-47bd-9565-472d92c80563)
![image](https://github.com/No0ne/ps2x2pico/assets/164865558/95724202-2e02-46b5-b4ae-8bec968e55d6)

**Comment by No0ne** [comment] 2024-04-05 19:23
Ha, this is working, just tested on my v4 mini! :)
For testing you have to leave the top board disconnnected as it routes the serial thru the RS232 converter to the RJ45 jack.

Jumper Pico GPIO22, 2 and 3 to GND (remove any other jumper).
Connect the Pico as shown in the photo bellow:
![screenshot](https://github.com/No0ne/ps2x2pico/assets/716129/06f38a5f-109a-4b5e-8855-c8c5c73e34eb)


Add the following to your /etc/kvmd/override.yaml:
```
kvmd:
    hid:
        type: serial
        device: /dev/ttyAMA0
        reset_pin: -1
```

Remove the following from your /boot/cmdline.txt:
```
console=serial0,115200
```

Then you should have a PS/2 keyboard an USB mouse.

**Comment by naplesap** [comment] 2024-04-05 19:52
> Ha, this is working, just tested on my v4 mini! :) For testing you have to leave the top board disconnnected as it routes the serial thru the RS232 converter to the RJ45 jack.
> 
> Add the following to your /etc/kvmd/override.yaml:
> 
> ```
> kvmd:
>     hid:
>         type: serial
>         device: /dev/ttyAMA0
>         reset_pin: -1
> ```
> 
> Remove the following from your /boot/cmdline.txt:
> 
> ```
> console=serial0,115200
> ```
> 
> Reboot, and then you should have a PS/2 keyboard an USB mouse.

Just to confirm, I would use `pico-hid.uf2` on the pico, correct?

**Comment by No0ne** [comment] 2024-04-05 19:55
any of the uf2 should work, try the offical first

**Comment by naplesap** [comment] 2024-04-06 17:47
> Ha, this is working, just tested on my v4 mini! :) For testing you have to leave the top board disconnnected as it routes the serial thru the RS232 converter to the RJ45 jack.
> 
> Jumper Pico GPIO22, 2 and 3 to GND (remove any other jumper). Connect the Pico as shown in the photo bellow: > Add the following to your /etc/kvmd/override.yaml:
> 
> ```
> kvmd:
>     hid:
>         type: serial
>         device: /dev/ttyAMA0
>         reset_pin: -1
> ```
> 
> Remove the following from your /boot/cmdline.txt:
> 
> ```
> console=serial0,115200
> ```
> 
> Reboot, and then you should have a PS/2 keyboard an USB mouse.

IT WORKS!!!! This is huge!! You have no idea how grateful I am!

**Comment by No0ne** [comment] 2024-04-06 19:19
Cool! I closed the issue with the two PIO USB devices then.

**Comment by No0ne** [comment] 2024-04-06 19:19
Cool! I closed the issue with the two PIO USB devices then.

May I close this one too?

**Comment by naplesap** [comment] 2024-04-06 22:57
Yes. Thank you so much for all of your help. It’s greatly appreciated. I’ll dig out the micrometer to see if I can plug this into the USB-C or RJ-45 ports.

**Comment by No0ne** [comment] 2024-04-07 02:15
On the USB-C port: No, theres a CP210n in the way!

On the RJ45: Maybe, theres a MAX232 in the way. You would need another MAX232 and four 10μF.

The easiest would be another pico running this: https://github.com/Noltari/pico-uart-bridge
And then connect GPIO16/17 from this to GPIO21/20 on the existing pico.

**Comment by No0ne** [comment] 2024-04-09 16:28
Ok I will look into the paste feature!

**Comment by No0ne** [comment] 2024-05-19 14:39
I checked that, it works if I make the output queue larger, but I don't know how much memory this needs on the pico.
How many character would you like to paste?

**Closed** 2024-06-14 16:33 UTC
